import type { PassengerKind } from './PassengerTypes';
import type { BossKind } from './bosses';

export interface LevelDef {
  id: number;
  stationEn: string;
  stationZh: string;
  flavourEn: string;
  flavourZh: string;
  density: number; // 0–10
  timer: number; // seconds
  /** Relative weights for special spawns */
  mix: Partial<Record<PassengerKind, number>>;
  /** Boarding pressure: 0–1 for regular levels; >1 = event surge (L100). */
  pressure: number;
  playable: boolean;
  /** Show a full intro card before the timer (first time / always on this level id). */
  introKind?: PassengerKind;
  /** Small HUD tip chip while playing (reinforce / remind). */
  tipKind?: PassengerKind;
  /** v0.7: override how many door bays open (default by level id: 3 → 2 from L8 → 1 from L16). 2 = relief level. */
  openDoors?: 1 | 2 | 3;
  /** v0.7: exam level (L99 final approach): all special types mixed. */
  exam?: boolean;
  /** v0.7: boss level — one oversized "king" per listed type (L20–L90 every 10; all eight at L100). */
  boss?: BossKind[];
}

const normalsOnly = (): LevelDef['mix'] => ({ normal: 10 });

const mixOf = (extra: Partial<Record<PassengerKind, number>>): LevelDef['mix'] => ({
  normal: 10,
  ...extra,
});

/**
 * v0.5.0 — ~10–15 s levels, staged special intros (see docs/LEVELS.md /
 * /workspace/review/LEVEL_PLAN_v05.md). L1–5 normals only; L6 luggage, L8 squat, then L9/12/15/18/21
 * introduce one type each; v0.6.3: L26 introduces 大聲公 Loudmouth (reinforced 27, mixed 29/30/100);
 * L100 fireworks finale.
 */
export const LEVELS: LevelDef[] = [
  {
    id: 1,
    stationEn: 'Sheung Yuen',
    stationZh: '上圓',
    flavourEn: 'Mid-morning quiet',
    flavourZh: '早上人少',
    density: 6,
    timer: 11,
    mix: normalsOnly(),
    pressure: 0.08,
    playable: true,
  },
  {
    id: 2,
    stationEn: 'Bastion Hill',
    stationZh: '堡壘山',
    flavourEn: 'Lunch trickle',
    flavourZh: '午飯時段',
    density: 6,
    timer: 11,
    mix: normalsOnly(),
    pressure: 0.10,
    playable: true,
  },
  {
    id: 3,
    stationEn: 'Gu Ching',
    stationZh: '古城',
    flavourEn: 'After-school',
    flavourZh: '放學潮',
    density: 6,
    timer: 11,
    mix: normalsOnly(),
    pressure: 0.15,
    playable: true,
  },
  {
    id: 4,
    stationEn: 'Koi Stream',
    stationZh: '鯉魚涌',
    flavourEn: 'Office spill',
    flavourZh: '放工潮',
    density: 7,
    timer: 11,
    mix: normalsOnly(),
    pressure: 0.20,
    playable: true,
  },
  {
    id: 5,
    stationEn: 'North Spot',
    stationZh: '北點',
    flavourEn: 'Evening peak start',
    flavourZh: '晚高峰開始',
    density: 7,
    timer: 11,
    mix: normalsOnly(),
    pressure: 0.25,
    playable: true,
  },
  {
    id: 6,
    stationEn: 'Causeway Bay Village',
    stationZh: '銅鑼灣村',
    flavourEn: 'Weekend shoppers',
    flavourZh: '週末購物',
    density: 6,
    timer: 11,
    mix: mixOf({ luggage: 4 }),
    pressure: 0.29,
    playable: true,
    introKind: 'luggage',
  },
  {
    id: 7,
    stationEn: 'Tin Wong',
    stationZh: '天王',
    flavourEn: 'Temple fair spill',
    flavourZh: '廟會散場',
    density: 6,
    timer: 12,
    mix: mixOf({ luggage: 5 }),
    pressure: 0.38,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 8,
    stationEn: 'Wan Neoi',
    stationZh: '灣女',
    flavourEn: 'Platform squatters',
    flavourZh: '月台踎低黨',
    density: 6,
    timer: 15,
    mix: mixOf({ squat: 4 }),
    pressure: 0.35,
    playable: true,
    introKind: 'squat',
  },
  {
    id: 9,
    stationEn: 'Silver Bell',
    stationZh: '銀鐘',
    flavourEn: 'Cross-platform crush',
    flavourZh: '轉車迫爆',
    density: 6,
    timer: 15,
    mix: mixOf({ stench: 4 }),
    pressure: 0.38,
    playable: true,
    introKind: 'stench',
  },
  {
    id: 10,
    stationEn: 'Central Yuen',
    stationZh: '中圓',
    flavourEn: 'Fri 18:30',
    flavourZh: '金曜傍晚',
    density: 7,
    timer: 15,
    mix: mixOf({ stench: 5 }),
    pressure: 0.35,
    playable: true,
    tipKind: 'stench',
  },
  {
    id: 11,
    stationEn: 'Hong City',
    stationZh: '香城',
    flavourEn: 'Airport transfer vibe',
    flavourZh: '機場轉車感',
    density: 7,
    timer: 19,
    mix: mixOf({ stench: 3, luggage: 3 }),
    pressure: 0.35,
    playable: true,
    tipKind: 'stench',
  },
  {
    id: 12,
    stationEn: 'Nine-Head Dragon',
    stationZh: '九頭龍',
    flavourEn: 'Tourist wave',
    flavourZh: '遊客潮',
    density: 6,
    timer: 11,
    mix: mixOf({ family: 5 }),
    pressure: 0.51,
    playable: true,
    introKind: 'family',
  },
  {
    id: 13,
    stationEn: 'Aa Wan',
    stationZh: '亞運',
    flavourEn: 'Concert let-out',
    flavourZh: '演唱會散場',
    density: 7,
    timer: 11,
    mix: mixOf({ family: 5 }),
    pressure: 0.44,
    playable: true,
    tipKind: 'family',
  },
  {
    id: 14,
    stationEn: 'Mong Gok',
    stationZh: '望角',
    flavourEn: 'Sat night',
    flavourZh: '週六夜晚',
    density: 8,
    timer: 12,
    mix: mixOf({ family: 4, luggage: 3 }),
    pressure: 0.43,
    playable: true,
    tipKind: 'family',
  },
  {
    id: 15,
    stationEn: 'Gong Jyu',
    stationZh: '公主',
    flavourEn: 'Calm then surge',
    flavourZh: '突然湧入',
    density: 7,
    timer: 11,
    mix: mixOf({ brat: 5 }),
    pressure: 0.79,
    playable: true,
    introKind: 'brat',
  },
  {
    id: 16,
    stationEn: 'Yam Chow',
    stationZh: '欽洲',
    flavourEn: 'Market close',
    flavourZh: '墟市收檔',
    density: 7,
    timer: 11,
    mix: mixOf({ brat: 5 }),
    pressure: 0.43,
    playable: true,
    tipKind: 'brat',
  },
  {
    id: 17,
    stationEn: 'Lai Chi Gok',
    stationZh: '荔枝角',
    flavourEn: 'Typhoon signal eve',
    flavourZh: '打風前夕',
    density: 7,
    timer: 14,
    mix: mixOf({ brat: 4, stench: 3 }),
    pressure: 0.41,
    playable: true,
    tipKind: 'brat',
  },
  {
    id: 18,
    stationEn: 'Chuen Jik',
    stationZh: '荃直',
    flavourEn: 'Terminal dump',
    flavourZh: '總站瀉人',
    density: 7,
    timer: 14,
    mix: mixOf({ couple: 5 }),
    pressure: 0.49,
    playable: true,
    introKind: 'couple',
  },
  {
    id: 19,
    stationEn: 'Hung Kwun',
    stationZh: '紅館',
    flavourEn: 'Through-train fantasy',
    flavourZh: '過境幻想',
    density: 8,
    timer: 14,
    mix: mixOf({ couple: 5 }),
    pressure: 0.51,
    playable: true,
    tipKind: 'couple',
  },
  {
    id: 20,
    stationEn: 'Dun East',
    stationZh: '頓東',
    flavourEn: 'Boss: Suitcase King',
    flavourZh: '頭目：行李箱大王',
    density: 8,
    timer: 17,
    mix: mixOf({ couple: 3, family: 2, luggage: 1 }),
    pressure: 0.47,
    playable: true,
    boss: ['luggage'],
    tipKind: 'luggage',
  },
  {
    id: 21,
    stationEn: 'Yuen Kwok',
    stationZh: '元國',
    flavourEn: 'New Territories rush',
    flavourZh: '新界趕車',
    density: 7,
    timer: 14,
    mix: mixOf({ angry: 5 }),
    pressure: 0.48,
    playable: true,
    introKind: 'angry',
  },
  {
    id: 22,
    stationEn: 'Long Ping Flat',
    stationZh: '塱平',
    flavourEn: 'Estate evening',
    flavourZh: '屋邨傍晚',
    density: 8,
    timer: 14,
    mix: mixOf({ angry: 5 }),
    pressure: 0.44,
    playable: true,
    tipKind: 'angry',
  },
  {
    id: 23,
    stationEn: 'Sheung Yuen',
    stationZh: '上圓',
    flavourEn: 'Late return',
    flavourZh: '夜歸',
    density: 7,
    timer: 20,
    mix: mixOf({ angry: 4, luggage: 3 }),
    pressure: 0.48,
    playable: true,
    tipKind: 'angry',
  },
  {
    id: 24,
    stationEn: 'Bastion Hill',
    stationZh: '堡壘山',
    flavourEn: 'Mix exam A',
    flavourZh: '綜合測驗甲',
    density: 7,
    timer: 20,
    mix: mixOf({ luggage: 2, squat: 2, stench: 2, family: 2 }),
    pressure: 0.37,
    playable: true,
    tipKind: 'squat',
  },
  {
    id: 25,
    stationEn: 'Gu Ching',
    stationZh: '古城',
    flavourEn: 'Mix exam B',
    flavourZh: '綜合測驗乙',
    density: 9,
    timer: 13,
    mix: mixOf({ brat: 4, couple: 4 }),
    pressure: 0.65,
    playable: true,
  },
  {
    id: 26,
    stationEn: 'Koi Stream',
    stationZh: '鯉魚涌',
    flavourEn: 'Phone-call carriage',
    flavourZh: '講電話車廂',
    density: 8,
    timer: 16,
    mix: mixOf({ loud: 1 }),
    pressure: 0.58,
    playable: true,
    introKind: 'loud',
  },
  {
    id: 27,
    stationEn: 'North Spot',
    stationZh: '北點',
    flavourEn: 'Boarding wall',
    flavourZh: '逼上車牆',
    density: 8,
    timer: 21,
    mix: mixOf({ luggage: 2, squat: 2, stench: 2, family: 2, brat: 2, couple: 2, angry: 2, loud: 1 }),
    pressure: 0.54,
    playable: true,
    tipKind: 'loud',
  },
  {
    id: 28,
    stationEn: 'Causeway Bay Village',
    stationZh: '銅鑼灣村',
    flavourEn: 'Suitcase maze',
    flavourZh: '喼迷宮',
    density: 7,
    timer: 21,
    mix: mixOf({ luggage: 3 }),
    pressure: 0.35,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 29,
    stationEn: 'Tin Wong',
    stationZh: '天王',
    flavourEn: 'Pressure spike',
    flavourZh: '壓力高峰',
    density: 10,
    timer: 20,
    mix: mixOf({ angry: 4, family: 3, stench: 3, loud: 0.8 }),
    pressure: 0.91,
    playable: true,
  },
  {
    id: 30,
    stationEn: 'Wan Neoi',
    stationZh: '灣女',
    flavourEn: 'Boss: Stink Fox King',
    flavourZh: '頭目：臭狐王',
    density: 10,
    timer: 25,
    mix: mixOf({ luggage: 2, squat: 2, stench: 2, family: 2, brat: 2, couple: 2, angry: 2, loud: 0.8 }),
    pressure: 0.39,
    playable: true,
    boss: ['stench'],
  },
  // v0.7 — L31–99 BEGIN (generated from the design table; tune here)
  {
    id: 31,
    stationEn: 'East Ying Pun',
    stationZh: '東營盤',
    flavourEn: 'School run',
    flavourZh: '返學潮',
    density: 9,
    timer: 18,
    mix: mixOf({ luggage: 2, brat: 2 }),
    pressure: 0.63,
    playable: true,
  },
  {
    id: 32,
    stationEn: 'Hong City University',
    stationZh: '香城大學',
    flavourEn: 'Campus couples',
    flavourZh: '校園情侶',
    density: 9,
    timer: 15,
    mix: mixOf({ couple: 3, loud: 1 }),
    pressure: 0.73,
    playable: true,
    tipKind: 'couple',
  },
  {
    id: 33,
    stationEn: 'Down-to-Earth Town',
    stationZh: '堅貼地城',
    flavourEn: 'Weekend outing',
    flavourZh: '週末出遊',
    density: 8,
    timer: 12,
    mix: mixOf({ family: 3, squat: 2, luggage: 1.5 }),
    pressure: 0.98,
    playable: true,
    openDoors: 2,
  },
  {
    id: 34,
    stationEn: 'East Wan Ho',
    stationZh: '東灣河',
    flavourEn: 'Gym let-out',
    flavourZh: '健身散場',
    density: 9,
    timer: 16,
    mix: mixOf({ stench: 3, angry: 2 }),
    pressure: 0.76,
    playable: true,
  },
  {
    id: 35,
    stationEn: 'Bamboo Kei Wan',
    stationZh: '竹箕灣',
    flavourEn: 'Market haul',
    flavourZh: '街市大包細包',
    density: 9,
    timer: 19,
    mix: mixOf({ luggage: 1.5, squat: 1, brat: 1 }),
    pressure: 0.53,
    playable: true,
  },
  {
    id: 36,
    stationEn: 'Shepherd Boy Chuen',
    stationZh: '牧童邨',
    flavourEn: 'Kids\' day out',
    flavourZh: '兒童節',
    density: 9,
    timer: 15,
    mix: mixOf({ brat: 3, family: 2, luggage: 1.5 }),
    pressure: 0.80,
    playable: true,
  },
  {
    id: 37,
    stationEn: 'Chai Kong',
    stationZh: '柴港',
    flavourEn: 'Shift change',
    flavourZh: '轉更',
    density: 9,
    timer: 14,
    mix: mixOf({ angry: 3, loud: 1.2 }),
    pressure: 0.61,
    playable: true,
    tipKind: 'angry',
  },
  {
    id: 38,
    stationEn: 'Yau Ma Sky',
    stationZh: '油麻天',
    flavourEn: 'Night market',
    flavourZh: '夜市',
    density: 9,
    timer: 16,
    mix: mixOf({ stench: 2, couple: 2, loud: 1 }),
    pressure: 0.68,
    playable: true,
  },
  {
    id: 39,
    stationEn: 'Michael',
    stationZh: '米高',
    flavourEn: 'Basketball fans',
    flavourZh: '球迷散場',
    density: 9,
    timer: 17,
    mix: mixOf({ brat: 2, angry: 2, luggage: 2 }),
    pressure: 0.67,
    playable: true,
  },
  {
    id: 40,
    stationEn: 'Short Sand Bay',
    stationZh: '短沙灣',
    flavourEn: 'Boss: Squat King',
    flavourZh: '頭目：踎低王',
    density: 9,
    timer: 25,
    mix: mixOf({ squat: 2, stench: 1, luggage: 1, brat: 1, loud: 0.5 }),
    pressure: 0.35,
    playable: true,
    boss: ['squat'],
  },
  {
    id: 41,
    stationEn: 'Lai Ching',
    stationZh: '荔晴',
    flavourEn: 'Interchange rush',
    flavourZh: '轉車潮',
    density: 9,
    timer: 21,
    mix: mixOf({ luggage: 2, loud: 1 }),
    pressure: 0.52,
    playable: true,
  },
  {
    id: 42,
    stationEn: 'Kwai Kwong',
    stationZh: '葵廣',
    flavourEn: 'Mall closing',
    flavourZh: '商場關門',
    density: 9,
    timer: 14,
    mix: mixOf({ family: 3, couple: 2 }),
    pressure: 0.74,
    playable: true,
  },
  {
    id: 43,
    stationEn: 'Kwai Wong',
    stationZh: '葵旺',
    flavourEn: 'Lunch queue',
    flavourZh: '排隊食飯',
    density: 8,
    timer: 14,
    mix: mixOf({ squat: 3, stench: 2, luggage: 1.5 }),
    pressure: 0.62,
    playable: true,
    openDoors: 2,
  },
  {
    id: 44,
    stationEn: 'Big Wok Mouth',
    stationZh: '大鍋口',
    flavourEn: 'Hot pot night',
    flavourZh: '打邊爐散場',
    density: 9,
    timer: 12,
    mix: mixOf({ angry: 3, brat: 2 }),
    pressure: 0.72,
    playable: true,
  },
  {
    id: 45,
    stationEn: 'Tsuen Wan East',
    stationZh: '荃灣東',
    flavourEn: 'Holiday departures',
    flavourZh: '放假出發',
    density: 9,
    timer: 20,
    mix: mixOf({ luggage: 2, family: 2, loud: 0.8 }),
    pressure: 0.63,
    playable: true,
  },
  {
    id: 46,
    stationEn: 'Shek Kip Head',
    stationZh: '石硤頭',
    flavourEn: 'Old estate',
    flavourZh: '舊屋邨',
    density: 9,
    timer: 20,
    mix: mixOf({ stench: 3, squat: 2, brat: 1 }),
    pressure: 0.67,
    playable: true,
  },
  {
    id: 47,
    stationEn: 'Kowloon University',
    stationZh: '九龍大學',
    flavourEn: 'Uni open day',
    flavourZh: '大學開放日',
    density: 9,
    timer: 14,
    mix: mixOf({ couple: 3, loud: 1.2 }),
    pressure: 0.74,
    playable: true,
    tipKind: 'loud',
  },
  {
    id: 48,
    stationEn: 'Tiger',
    stationZh: '老虎',
    flavourEn: 'Temple fair',
    flavourZh: '廟會',
    density: 9,
    timer: 14,
    mix: mixOf({ angry: 3, family: 2 }),
    pressure: 0.80,
    playable: true,
  },
  {
    id: 49,
    stationEn: 'Blue Tai Sin',
    stationZh: '藍大仙',
    flavourEn: 'Lunar new year',
    flavourZh: '年初一拜神',
    density: 9,
    timer: 16,
    mix: mixOf({ family: 3, loud: 1, stench: 2 }),
    pressure: 0.81,
    playable: true,
  },
  {
    id: 50,
    stationEn: 'Gem Hill',
    stationZh: '寶石山',
    flavourEn: 'Boss: The Patriarch',
    flavourZh: '頭目：大家長',
    density: 9,
    timer: 17,
    mix: mixOf({ family: 2, couple: 1.5, squat: 1, angry: 1 }),
    pressure: 0.73,
    playable: true,
    boss: ['family'],
  },
  {
    id: 51,
    stationEn: 'Choi Wan',
    stationZh: '彩雲',
    flavourEn: 'Rainbow parade',
    flavourZh: '彩虹巡遊',
    density: 9,
    timer: 14,
    mix: mixOf({ brat: 3, couple: 2, luggage: 1.5 }),
    pressure: 0.61,
    playable: true,
  },
  {
    id: 52,
    stationEn: 'Nine Phoenix Bay',
    stationZh: '九鳳灣',
    flavourEn: 'Office towers',
    flavourZh: '寫字樓放工',
    density: 9,
    timer: 19,
    mix: mixOf({ luggage: 2, angry: 2, loud: 1 }),
    pressure: 0.74,
    playable: true,
  },
  {
    id: 53,
    stationEn: 'Ox Tail Point',
    stationZh: '牛尾角',
    flavourEn: 'Factory outlet',
    flavourZh: '工廈開倉',
    density: 8,
    timer: 13,
    mix: mixOf({ squat: 3, family: 2, luggage: 1.5 }),
    pressure: 0.93,
    playable: true,
    openDoors: 2,
  },
  {
    id: 54,
    stationEn: 'Kwun Hall',
    stationZh: '觀堂',
    flavourEn: 'Rush-hour core',
    flavourZh: '繁忙時間',
    density: 9,
    timer: 16,
    mix: mixOf({ angry: 3, stench: 2, loud: 1 }),
    pressure: 0.75,
    playable: true,
  },
  {
    id: 55,
    stationEn: 'Green Field',
    stationZh: '綠田',
    flavourEn: 'Estate school run',
    flavourZh: '屋邨返學',
    density: 9,
    timer: 16,
    mix: mixOf({ family: 2, brat: 2, luggage: 2 }),
    pressure: 0.78,
    playable: true,
  },
  {
    id: 56,
    stationEn: 'Oil Soup',
    stationZh: '油湯',
    flavourEn: 'Seafood street',
    flavourZh: '海鮮街',
    density: 9,
    timer: 15,
    mix: mixOf({ stench: 4, loud: 1 }),
    pressure: 0.76,
    playable: true,
    tipKind: 'stench',
  },
  {
    id: 57,
    stationEn: 'Tiu Keng Peak',
    stationZh: '調景峰',
    flavourEn: 'Hillside commute',
    flavourZh: '上山返工',
    density: 9,
    timer: 18,
    mix: mixOf({ couple: 3, squat: 2 }),
    pressure: 0.68,
    playable: true,
  },
  {
    id: 58,
    stationEn: 'Tseung Bing O',
    stationZh: '將兵澳',
    flavourEn: 'New town',
    flavourZh: '新市鎮',
    density: 9,
    timer: 21,
    mix: mixOf({ luggage: 2, brat: 2, loud: 1 }),
    pressure: 0.92,
    playable: true,
  },
  {
    id: 59,
    stationEn: 'Hang Mei',
    stationZh: '坑尾',
    flavourEn: 'Construction crews',
    flavourZh: '地盤收工',
    density: 9,
    timer: 17,
    mix: mixOf({ angry: 3, squat: 2 }),
    pressure: 0.75,
    playable: true,
  },
  {
    id: 60,
    stationEn: 'Po Chi Lam',
    stationZh: '寶之林',
    flavourEn: 'Boss: Brat King',
    flavourZh: '頭目：衰仔王',
    density: 9,
    timer: 15,
    mix: mixOf({ brat: 2, angry: 1.5, squat: 1.5, family: 1, loud: 0.6 }),
    pressure: 0.98,
    playable: true,
    boss: ['brat'],
  },
  {
    id: 61,
    stationEn: 'Hong Town',
    stationZh: '康鎮',
    flavourEn: 'Seaside flats',
    flavourZh: '海景樓',
    density: 10,
    timer: 12,
    mix: mixOf({ family: 3, couple: 2, loud: 1 }),
    pressure: 0.89,
    playable: true,
  },
  {
    id: 62,
    stationEn: 'Blue Po',
    stationZh: '藍埔',
    flavourEn: 'Cruise day',
    flavourZh: '郵輪日',
    density: 10,
    timer: 18,
    mix: mixOf({ luggage: 2, stench: 2 }),
    pressure: 0.74,
    playable: true,
  },
  {
    id: 63,
    stationEn: 'Ho Mo Tin',
    stationZh: '何武田',
    flavourEn: 'Prep schools',
    flavourZh: '名校區',
    density: 10,
    timer: 15,
    mix: mixOf({ brat: 3, angry: 2, luggage: 1.5 }),
    pressure: 0.98,
    playable: true,
  },
  {
    id: 64,
    stationEn: 'Papaya Bay',
    stationZh: '木瓜灣',
    flavourEn: 'Old district',
    flavourZh: '舊區',
    density: 9,
    timer: 12,
    mix: mixOf({ squat: 3, family: 2, loud: 1, luggage: 1.5 }),
    pressure: 0.98,
    playable: true,
    openDoors: 2,
  },
  {
    id: 65,
    stationEn: 'Chun Wong Terrace',
    stationZh: '秦王臺',
    flavourEn: 'History walk',
    flavourZh: '古蹟遊',
    density: 10,
    timer: 12,
    mix: mixOf({ couple: 3, stench: 2 }),
    pressure: 0.82,
    playable: true,
  },
  {
    id: 66,
    stationEn: 'Old Airport',
    stationZh: '舊機場',
    flavourEn: 'Stadium event',
    flavourZh: '大球場散場',
    density: 10,
    timer: 16,
    mix: mixOf({ luggage: 2, angry: 2 }),
    pressure: 0.70,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 67,
    stationEn: 'Hin Lou',
    stationZh: '顯路',
    flavourEn: 'Tunnel traffic',
    flavourZh: '隧道塞車',
    density: 10,
    timer: 19,
    mix: mixOf({ stench: 2, squat: 2, loud: 1.2 }),
    pressure: 0.82,
    playable: true,
  },
  {
    id: 68,
    stationEn: 'Che Po Temple',
    stationZh: '車婆廟',
    flavourEn: 'Temple crowds',
    flavourZh: '車公誕',
    density: 10,
    timer: 13,
    mix: mixOf({ family: 3, angry: 2, brat: 1, luggage: 1.5 }),
    pressure: 0.84,
    playable: true,
  },
  {
    id: 69,
    stationEn: 'Sha Tin Ring',
    stationZh: '沙田圈',
    flavourEn: 'Riverside',
    flavourZh: '河畔',
    density: 10,
    timer: 21,
    mix: mixOf({ couple: 2, squat: 2, luggage: 2 }),
    pressure: 0.77,
    playable: true,
  },
  {
    id: 70,
    stationEn: 'City Two',
    stationZh: '第二城',
    flavourEn: 'Boss: Clingy Couple Royals',
    flavourZh: '頭目：黏身情侶王',
    density: 9,
    timer: 18,
    mix: mixOf({ couple: 2, luggage: 1.5, stench: 1, brat: 1 }),
    pressure: 0.80,
    playable: true,
    boss: ['couple'],
  },
  {
    id: 71,
    stationEn: 'Iron Gate',
    stationZh: '鐵門',
    flavourEn: 'Industrial belt',
    flavourZh: '工業區',
    density: 10,
    timer: 17,
    mix: mixOf({ angry: 3, luggage: 2 }),
    pressure: 0.84,
    playable: true,
  },
  {
    id: 72,
    stationEn: 'Big Fire Pit',
    stationZh: '大火坑',
    flavourEn: 'Barbecue weekend',
    flavourZh: '燒烤週末',
    density: 10,
    timer: 15,
    mix: mixOf({ stench: 3, brat: 2, loud: 1, luggage: 1.5 }),
    pressure: 0.84,
    playable: true,
  },
  {
    id: 73,
    stationEn: 'Heng Lok',
    stationZh: '恒樂',
    flavourEn: 'Quiet estate',
    flavourZh: '屋苑',
    density: 10,
    timer: 20,
    mix: mixOf({ family: 2, squat: 2, luggage: 2, angry: 2 }),
    pressure: 0.95,
    playable: true,
  },
  {
    id: 74,
    stationEn: 'Ma On Sea',
    stationZh: '馬鞍海',
    flavourEn: 'Mountain hikers',
    flavourZh: '行山客',
    density: 10,
    timer: 12,
    mix: mixOf({ couple: 2, angry: 2, loud: 1.2 }),
    pressure: 0.88,
    playable: true,
  },
  {
    id: 75,
    stationEn: 'Wu Kai Rock',
    stationZh: '烏溪石',
    flavourEn: 'End of the line',
    flavourZh: '總站',
    density: 10,
    timer: 15,
    mix: mixOf({ luggage: 2, brat: 2 }),
    pressure: 0.92,
    playable: true,
  },
  {
    id: 76,
    stationEn: 'Bak Cheong',
    stationZh: '北昌',
    flavourEn: 'Interchange crush',
    flavourZh: '轉車人潮',
    density: 10,
    timer: 13,
    mix: mixOf({ stench: 2, family: 2, angry: 2 }),
    pressure: 0.86,
    playable: true,
  },
  {
    id: 77,
    stationEn: 'Tung Si Din',
    stationZh: '痌屎癲',
    flavourEn: 'Harbourside',
    flavourZh: '海傍',
    density: 10,
    timer: 19,
    mix: mixOf({ squat: 3, couple: 2, loud: 1.2 }),
    pressure: 0.86,
    playable: true,
    tipKind: 'squat',
  },
  {
    id: 78,
    stationEn: 'Kam Ha Road',
    stationZh: '錦下路',
    flavourEn: 'Country park',
    flavourZh: '郊野公園',
    density: 10,
    timer: 17,
    mix: mixOf({ luggage: 2, angry: 2, stench: 1 }),
    pressure: 0.87,
    playable: true,
  },
  {
    id: 79,
    stationEn: 'Dei Shui Wai',
    stationZh: '地水圍',
    flavourEn: 'Wetland trip',
    flavourZh: '濕地遊',
    density: 10,
    timer: 12,
    mix: mixOf({ family: 3, brat: 3, luggage: 1.5 }),
    pressure: 0.91,
    playable: true,
  },
  {
    id: 80,
    stationEn: 'Siu Gin',
    stationZh: '兆健',
    flavourEn: 'Boss: Grumpy Hog King',
    flavourZh: '頭目：嬲嬲豬王',
    density: 9,
    timer: 14,
    mix: mixOf({ angry: 2, brat: 1.5, squat: 1, loud: 0.8 }),
    pressure: 0.98,
    playable: true,
    boss: ['angry'],
  },
  {
    id: 81,
    stationEn: 'Tuen Bing',
    stationZh: '屯兵',
    flavourEn: 'Garrison town',
    flavourZh: '屯兵重鎮',
    density: 10,
    timer: 16,
    mix: mixOf({ angry: 3, squat: 2, loud: 1 }),
    pressure: 0.85,
    playable: true,
  },
  {
    id: 82,
    stationEn: 'Mong Kok West',
    stationZh: '旺角西',
    flavourEn: 'Shopping spree',
    flavourZh: '掃貨',
    density: 10,
    timer: 15,
    mix: mixOf({ couple: 3, luggage: 2 }),
    pressure: 0.85,
    playable: true,
  },
  {
    id: 83,
    stationEn: 'Siu Wai',
    stationZh: '小圍',
    flavourEn: 'Junction',
    flavourZh: '大站轉車',
    density: 10,
    timer: 14,
    mix: mixOf({ family: 2, stench: 2, brat: 2, luggage: 1.5 }),
    pressure: 0.91,
    playable: true,
  },
  {
    id: 84,
    stationEn: 'Old City',
    stationZh: '舊城市',
    flavourEn: 'Old city centre',
    flavourZh: '舊城中心',
    density: 10,
    timer: 17,
    mix: mixOf({ angry: 3, luggage: 2, loud: 1.2 }),
    pressure: 0.89,
    playable: true,
  },
  {
    id: 85,
    stationEn: 'Bing Tan',
    stationZh: '冰炭',
    flavourEn: 'Workshop lane',
    flavourZh: '工場街',
    density: 9,
    timer: 11,
    mix: mixOf({ squat: 3, stench: 2, luggage: 1.5 }),
    pressure: 0.91,
    playable: true,
    openDoors: 2,
  },
  {
    id: 86,
    stationEn: 'Ox Course',
    stationZh: '牛場',
    flavourEn: 'Race day',
    flavourZh: '賽馬日',
    density: 10,
    timer: 14,
    mix: mixOf({ angry: 4, couple: 2, luggage: 1.5 }),
    pressure: 0.78,
    playable: true,
    tipKind: 'angry',
  },
  {
    id: 87,
    stationEn: 'Secondary School',
    stationZh: '中學',
    flavourEn: 'Exam season',
    flavourZh: '考試季',
    density: 10,
    timer: 13,
    mix: mixOf({ brat: 3, family: 2, loud: 1, luggage: 1.5 }),
    pressure: 0.98,
    playable: true,
  },
  {
    id: 88,
    stationEn: 'Tai Po Mart',
    stationZh: '大埔市',
    flavourEn: 'Market town',
    flavourZh: '墟日',
    density: 10,
    timer: 15,
    mix: mixOf({ luggage: 2, family: 2, stench: 1 }),
    pressure: 0.88,
    playable: true,
  },
  {
    id: 89,
    stationEn: 'Tai Ping',
    stationZh: '太平',
    flavourEn: 'Peaceful suburb',
    flavourZh: '太平郊區',
    density: 10,
    timer: 15,
    mix: mixOf({ couple: 3, squat: 2, loud: 1 }),
    pressure: 0.94,
    playable: true,
  },
  {
    id: 90,
    stationEn: 'Fan Hill',
    stationZh: '粉山',
    flavourEn: 'Boss: Loudmouth King',
    flavourZh: '頭目：大聲公王',
    density: 9,
    timer: 18,
    mix: mixOf({ loud: 1.2, angry: 1.5, stench: 1.5, couple: 1 }),
    pressure: 0.92,
    playable: true,
    boss: ['loud'],
  },
  {
    id: 91,
    stationEn: 'Ha Shui',
    stationZh: '下水',
    flavourEn: 'Border shoppers',
    flavourZh: '水貨客',
    density: 10,
    timer: 16,
    mix: mixOf({ luggage: 2, angry: 2 }),
    pressure: 0.98,
    playable: true,
  },
  {
    id: 92,
    stationEn: 'Lo Hoi',
    stationZh: '羅海',
    flavourEn: 'Border gate',
    flavourZh: '過關',
    density: 10,
    timer: 18,
    mix: mixOf({ luggage: 2, squat: 2, loud: 1 }),
    pressure: 0.80,
    playable: true,
  },
  {
    id: 93,
    stationEn: 'Mount Horse Isle',
    stationZh: '上馬洲',
    flavourEn: 'Last checkpoint',
    flavourZh: '最後一關',
    density: 10,
    timer: 13,
    mix: mixOf({ family: 3, angry: 2, stench: 1, luggage: 1.5 }),
    pressure: 0.89,
    playable: true,
  },
  {
    id: 94,
    stationEn: 'Tsing Saam',
    stationZh: '青衫',
    flavourEn: 'Bridge winds',
    flavourZh: '大橋風',
    density: 10,
    timer: 12,
    mix: mixOf({ stench: 3, couple: 2, loud: 1.2 }),
    pressure: 0.90,
    playable: true,
  },
  {
    id: 95,
    stationEn: 'Joyful Bay',
    stationZh: '歡澳',
    flavourEn: 'Theme park day',
    flavourZh: '主題樂園',
    density: 10,
    timer: 13,
    mix: mixOf({ family: 2, brat: 2, luggage: 2, angry: 3 }),
    pressure: 0.92,
    playable: true,
  },
  {
    id: 96,
    stationEn: 'West Chung',
    stationZh: '西涌',
    flavourEn: 'Airport town',
    flavourZh: '機場新市鎮',
    density: 10,
    timer: 13,
    mix: mixOf({ luggage: 2, family: 2, loud: 1 }),
    pressure: 0.85,
    playable: true,
  },
  {
    id: 97,
    stationEn: 'Aeroplane',
    stationZh: '飛機',
    flavourEn: 'Departures',
    flavourZh: '出發大堂',
    density: 10,
    timer: 13,
    mix: mixOf({ luggage: 2, angry: 2 }),
    pressure: 0.67,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 98,
    stationEn: 'Expo City',
    stationZh: '博覽城',
    flavourEn: 'Concert night',
    flavourZh: '演唱會散場',
    density: 10,
    timer: 13,
    mix: mixOf({ couple: 2, brat: 2, loud: 1.5, stench: 2, luggage: 1.5 }),
    pressure: 0.95,
    playable: true,
  },
  {
    id: 99,
    stationEn: 'Ocean Garden',
    stationZh: '海洋花園',
    flavourEn: 'Final approach',
    flavourZh: '終極前哨',
    density: 10,
    timer: 14,
    mix: mixOf({ luggage: 2, squat: 2, stench: 2, family: 2, brat: 2, couple: 2, angry: 3, loud: 1.5 }),
    pressure: 0.80,
    playable: true,
    exam: true,
  },
  // v0.7 — L31–99 END
  {
    id: 100,
    stationEn: 'Dun Sha Mouth',
    stationZh: '頓沙嘴',
    flavourEn: 'After fireworks',
    flavourZh: '十一煙花後',
    density: 8,
    timer: 27,
    mix: {
      normal: 2,
      angry: 7,
      luggage: 4,
      squat: 3,
      family: 3,
      couple: 2,
      stench: 2,
      brat: 1,
      loud: 1,
    },
    pressure: 0.90,
    playable: true,
    boss: ['luggage', 'stench', 'squat', 'family', 'brat', 'couple', 'angry', 'loud'],
  },
];

/** Level id that must be cleared before L100 unlocks (v0.7: was 30 → now 99). */
export const FINALE_UNLOCK_AFTER = 99;

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function playableLevels(): LevelDef[] {
  return LEVELS.filter((l) => l.playable);
}

/** How many agents to spawn from density 0–10 */
export function crowdCount(density: number): number {
  // v0.6: denser cars (was 6 + d·3.2). Cap soft via maxBodies.
  return Math.round(7 + density * 3.6);
}

/**
 * True if the player may start the fireworks finale. `highestCleared` counts L100 itself, so check
 * the cleared list for 99 explicitly. Players who already beat L100 before v0.7 keep it unlocked.
 */
export function isFinaleUnlocked(cleared: number[], _highestCleared?: number): boolean {
  return cleared.includes(FINALE_UNLOCK_AFTER) || cleared.includes(100);
}
