import type { PassengerKind } from './PassengerTypes';

export interface LevelDef {
  id: number;
  stationEn: string;
  stationZh: string;
  flavourEn: string;
  flavourZh: string;
  density: number; // 0–10
  timer: number; // seconds
  /** Relative weights for special spawns */
  mix: Partial<Record<PassengerKind, number>>;
  /** Boarding pressure: 0–1 for regular levels; >1 = event surge (L100). */
  pressure: number;
  playable: boolean;
  /** Show a full intro card before the timer (first time / always on this level id). */
  introKind?: PassengerKind;
  /** Small HUD tip chip while playing (reinforce / remind). */
  tipKind?: PassengerKind;
}

const normalsOnly = (): LevelDef['mix'] => ({ normal: 10 });

const mixOf = (extra: Partial<Record<PassengerKind, number>>): LevelDef['mix'] => ({
  normal: 10,
  ...extra,
});

/**
 * v0.5.0 — ~10–15 s levels, staged special intros (see docs/LEVELS.md /
 * /workspace/review/LEVEL_PLAN_v05.md). L1–5 normals only; L6/9/12/15/18/21
 * introduce one type each; L100 fireworks finale.
 */
export const LEVELS: LevelDef[] = [
  {
    id: 1,
    stationEn: 'Sheung Yuen',
    stationZh: '上圓',
    flavourEn: 'Mid-morning quiet',
    flavourZh: '早上人少',
    density: 5,
    timer: 14,
    mix: normalsOnly(),
    pressure: 0.08,
    playable: true,
  },
  {
    id: 2,
    stationEn: 'Bastion Hill',
    stationZh: '堡壘山',
    flavourEn: 'Lunch trickle',
    flavourZh: '午飯時段',
    density: 5,
    timer: 13,
    mix: normalsOnly(),
    pressure: 0.1,
    playable: true,
  },
  {
    id: 3,
    stationEn: 'Gu Ching',
    stationZh: '古城',
    flavourEn: 'After-school',
    flavourZh: '放學潮',
    density: 5,
    timer: 13,
    mix: normalsOnly(),
    pressure: 0.15,
    playable: true,
  },
  {
    id: 4,
    stationEn: 'Koi Stream',
    stationZh: '鯉魚涌',
    flavourEn: 'Office spill',
    flavourZh: '放工潮',
    density: 6,
    timer: 12,
    mix: normalsOnly(),
    pressure: 0.2,
    playable: true,
  },
  {
    id: 5,
    stationEn: 'North Spot',
    stationZh: '北點',
    flavourEn: 'Evening peak start',
    flavourZh: '晚高峰開始',
    density: 6,
    timer: 12,
    mix: normalsOnly(),
    pressure: 0.25,
    playable: true,
  },
  {
    id: 6,
    stationEn: 'Causeway Bay Village',
    stationZh: '銅鑼灣村',
    flavourEn: 'Weekend shoppers',
    flavourZh: '週末購物',
    density: 5,
    timer: 14,
    mix: mixOf({ luggage: 4 }),
    pressure: 0.25,
    playable: true,
    introKind: 'luggage',
  },
  {
    id: 7,
    stationEn: 'Tin Wong',
    stationZh: '天王',
    flavourEn: 'Temple fair spill',
    flavourZh: '廟會散場',
    density: 5,
    timer: 13,
    mix: mixOf({ luggage: 5 }),
    pressure: 0.3,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 8,
    stationEn: 'Wan Neoi',
    stationZh: '灣女',
    flavourEn: 'Conference let-out',
    flavourZh: '會議散場',
    density: 6,
    timer: 14,
    mix: mixOf({ luggage: 6 }),
    pressure: 0.3,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 9,
    stationEn: 'Silver Bell',
    stationZh: '銀鐘',
    flavourEn: 'Cross-platform crush',
    flavourZh: '轉車迫爆',
    density: 5,
    timer: 14,
    mix: mixOf({ stench: 4 }),
    pressure: 0.3,
    playable: true,
    introKind: 'stench',
  },
  {
    id: 10,
    stationEn: 'Central Yuen',
    stationZh: '中圓',
    flavourEn: 'Fri 18:30',
    flavourZh: '金曜傍晚',
    density: 6,
    timer: 13,
    mix: mixOf({ stench: 5 }),
    pressure: 0.35,
    playable: true,
    tipKind: 'stench',
  },
  {
    id: 11,
    stationEn: 'Hong City',
    stationZh: '香城',
    flavourEn: 'Airport transfer vibe',
    flavourZh: '機場轉車感',
    density: 6,
    timer: 14,
    mix: mixOf({ stench: 3, luggage: 3 }),
    pressure: 0.25,
    playable: true,
    tipKind: 'stench',
  },
  {
    id: 12,
    stationEn: 'Nine-Head Dragon',
    stationZh: '九頭龍',
    flavourEn: 'Tourist wave',
    flavourZh: '遊客潮',
    density: 5,
    timer: 14,
    mix: mixOf({ family: 5 }),
    pressure: 0.35,
    playable: true,
    introKind: 'family',
  },
  {
    id: 13,
    stationEn: 'Aa Wan',
    stationZh: '亞運',
    flavourEn: 'Concert let-out',
    flavourZh: '演唱會散場',
    density: 6,
    timer: 13,
    mix: mixOf({ family: 5 }),
    pressure: 0.4,
    playable: true,
    tipKind: 'family',
  },
  {
    id: 14,
    stationEn: 'Mong Gok',
    stationZh: '望角',
    flavourEn: 'Sat night',
    flavourZh: '週六夜晚',
    density: 7,
    timer: 14,
    mix: mixOf({ family: 4, luggage: 3 }),
    pressure: 0.45,
    playable: true,
    tipKind: 'family',
  },
  {
    id: 15,
    stationEn: 'Gong Jyu',
    stationZh: '公主',
    flavourEn: 'Calm then surge',
    flavourZh: '突然湧入',
    density: 6,
    timer: 14,
    mix: mixOf({ brat: 5 }),
    pressure: 0.4,
    playable: true,
    introKind: 'brat',
  },
  {
    id: 16,
    stationEn: 'Yam Chow',
    stationZh: '欽洲',
    flavourEn: 'Market close',
    flavourZh: '墟市收檔',
    density: 6,
    timer: 13,
    mix: mixOf({ brat: 5 }),
    pressure: 0.45,
    playable: true,
    tipKind: 'brat',
  },
  {
    id: 17,
    stationEn: 'Lai Chi Gok',
    stationZh: '荔枝角',
    flavourEn: 'Typhoon signal eve',
    flavourZh: '打風前夕',
    density: 6,
    timer: 15,
    mix: mixOf({ brat: 4, stench: 3 }),
    pressure: 0.4,
    playable: true,
    tipKind: 'brat',
  },
  {
    id: 18,
    stationEn: 'Chuen Jik',
    stationZh: '荃直',
    flavourEn: 'Terminal dump',
    flavourZh: '總站瀉人',
    density: 6,
    timer: 15,
    mix: mixOf({ couple: 5 }),
    pressure: 0.45,
    playable: true,
    introKind: 'couple',
  },
  {
    id: 19,
    stationEn: 'Maan Gwok',
    stationZh: '萬國',
    flavourEn: 'Through-train fantasy',
    flavourZh: '過境幻想',
    density: 7,
    timer: 14,
    mix: mixOf({ couple: 5 }),
    pressure: 0.5,
    playable: true,
    tipKind: 'couple',
  },
  {
    id: 20,
    stationEn: 'Dun East',
    stationZh: '頓東',
    flavourEn: 'Pre-fireworks',
    flavourZh: '煙花前',
    density: 7,
    timer: 15,
    mix: mixOf({ couple: 4, family: 3 }),
    pressure: 0.55,
    playable: true,
    tipKind: 'couple',
  },
  {
    id: 21,
    stationEn: 'Yuen Kwok',
    stationZh: '元國',
    flavourEn: 'New Territories rush',
    flavourZh: '新界趕車',
    density: 6,
    timer: 15,
    mix: mixOf({ angry: 5 }),
    pressure: 0.5,
    playable: true,
    introKind: 'angry',
  },
  {
    id: 22,
    stationEn: 'Long Ping Flat',
    stationZh: '塱平',
    flavourEn: 'Estate evening',
    flavourZh: '屋邨傍晚',
    density: 7,
    timer: 14,
    mix: mixOf({ angry: 5 }),
    pressure: 0.55,
    playable: true,
    tipKind: 'angry',
  },
  {
    id: 23,
    stationEn: 'Sheung Yuen',
    stationZh: '上圓',
    flavourEn: 'Late return',
    flavourZh: '夜歸',
    density: 6,
    timer: 16,
    mix: mixOf({ angry: 4, luggage: 3 }),
    pressure: 0.5,
    playable: true,
    tipKind: 'angry',
  },
  {
    id: 24,
    stationEn: 'Bastion Hill',
    stationZh: '堡壘山',
    flavourEn: 'Mix exam A',
    flavourZh: '綜合測驗甲',
    density: 6,
    timer: 17,
    mix: mixOf({ luggage: 2, stench: 2, family: 2 }),
    pressure: 0.4,
    playable: true,
  },
  {
    id: 25,
    stationEn: 'Gu Ching',
    stationZh: '古城',
    flavourEn: 'Mix exam B',
    flavourZh: '綜合測驗乙',
    density: 8,
    timer: 16,
    mix: mixOf({ brat: 4, couple: 4 }),
    pressure: 0.65,
    playable: true,
  },
  {
    id: 26,
    stationEn: 'Koi Stream',
    stationZh: '鯉魚涌',
    flavourEn: 'Mix exam C',
    flavourZh: '綜合測驗丙',
    density: 8,
    timer: 16,
    mix: mixOf({ angry: 4, couple: 4 }),
    pressure: 0.7,
    playable: true,
  },
  {
    id: 27,
    stationEn: 'North Spot',
    stationZh: '北點',
    flavourEn: 'Boarding wall',
    flavourZh: '逼上車牆',
    density: 7,
    timer: 17,
    mix: mixOf({ luggage: 2, stench: 2, family: 2, brat: 2, couple: 2, angry: 2 }),
    pressure: 0.6,
    playable: true,
  },
  {
    id: 28,
    stationEn: 'Causeway Bay Village',
    stationZh: '銅鑼灣村',
    flavourEn: 'Suitcase maze',
    flavourZh: '喼迷宮',
    density: 6,
    timer: 20,
    mix: mixOf({ luggage: 3 }),
    pressure: 0.35,
    playable: true,
    tipKind: 'luggage',
  },
  {
    id: 29,
    stationEn: 'Tin Wong',
    stationZh: '天王',
    flavourEn: 'Pressure spike',
    flavourZh: '壓力高峰',
    density: 9,
    timer: 17,
    mix: mixOf({ angry: 4, family: 3, stench: 3 }),
    pressure: 0.85,
    playable: true,
  },
  {
    id: 30,
    stationEn: 'Wan Neoi',
    stationZh: '灣女',
    flavourEn: 'Act boss',
    flavourZh: '關底',
    density: 9,
    timer: 18,
    mix: mixOf({ luggage: 2, stench: 2, family: 2, brat: 2, couple: 2, angry: 2 }),
    pressure: 0.9,
    playable: true,
  },
  {
    id: 100,
    stationEn: 'Dun Sha Mouth',
    stationZh: '頓沙嘴',
    flavourEn: 'After fireworks',
    flavourZh: '十一煙花後',
    density: 10,
    timer: 24,
    mix: {
      normal: 2,
      angry: 7,
      luggage: 5,
      family: 3,
      couple: 2,
      stench: 2,
      brat: 1,
    },
    pressure: 1.5,
    playable: true,
  },
];

/** Level id that must be cleared before L100 unlocks. */
export const FINALE_UNLOCK_AFTER = 30;

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function playableLevels(): LevelDef[] {
  return LEVELS.filter((l) => l.playable);
}

/** How many agents to spawn from density 0–10 */
export function crowdCount(density: number): number {
  return Math.round(6 + density * 3.2);
}

/** True if the player may start the fireworks finale. */
export function isFinaleUnlocked(cleared: number[], highestCleared: number): boolean {
  return cleared.includes(FINALE_UNLOCK_AFTER) || highestCleared >= FINALE_UNLOCK_AFTER;
}
